var gulp = require('gulp');
var autoprefixer = require('gulp-autoprefixer');
var sass = require('gulp-sass');
var replace = require('gulp-replace');

//
function handleError(error) {
    console.log(error);
    this.emit('end');
}

//
function generate(subreddit) {
    return gulp.src(`subreddits/${subreddit}.scss`)
        .pipe(sass(
            {
                outputStyle: 'compact',
            }
        )).on('error', handleError)
        .pipe(autoprefixer())
        .pipe(gulp.dest('build/'));
}

//
gulp.task('reddify', gulp.series(function() {
    return gulp.src(['build/*.css'])
        // Replace image names
        .pipe(replace(/url\("(.+)\.(?:png|jpg)"\)/g, 'url(%%$1%%)'))
        // Remove autogenerated prefix properties that reddit doesn't like
        .pipe(replace('-webkit-box-flex: 1;', ''))
        .pipe(replace('-ms-flex-positive: 1;', ''))
        // We aren't allowed to have a charset if we include unicode characters,
        // and we aren't allowed to use backslashes as a workaround either, so remove
        // the charset from the page.
        .pipe(replace('@charset "UTF-8";', ''))
        .pipe(gulp.dest('build/'));
}));

//
gulp.task('generate-spacex', gulp.series(() => {
    return generate('spacex');
}, 'reddify'));

//
gulp.task('generate-spacexlounge', gulp.series(() => {
    return generate('spacexlounge');
}, 'reddify'));